services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: academiapro
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/academiapro
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change}
      DEBUG: "false"
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  db_data:
