"""
Revision ID: c8ceaaf089ed
Revises: d5e4c1a2ec7c
Create Date: 2025-12-25 23:27:21.399162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c8ceaaf089ed'
down_revision: Union[str, None] = 'd5e4c1a2ec7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courseassignment',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('open_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('allow_late', sa.Boolean(), nullable=False),
    sa.Column('submission_type', sa.Enum('online', 'upload', 'link', name='assignmentsubmissiontypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courseassignment_course_id'), 'courseassignment', ['course_id'], unique=False)
    op.create_table('coursematerial',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_type', sa.Enum('file', 'link', 'text', 'embed', name='materialtypeenum'), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('visible_from', sa.DateTime(), nullable=True),
    sa.Column('visible_until', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coursematerial_course_id'), 'coursematerial', ['course_id'], unique=False)
    op.create_table('assignmentsubmission',
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'returned', 'graded', name='assignmentsubmissionstatusenum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('graded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['courseassignment.id'], ),
    sa.ForeignKeyConstraint(['graded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_assignment_submission_student')
    )
    op.create_index(op.f('ix_assignmentsubmission_assignment_id'), 'assignmentsubmission', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignmentsubmission_student_id'), 'assignmentsubmission', ['student_id'], unique=False)
    op.alter_column('appsetting', 'value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('appsetting', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('appsetting', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('course', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('course_program_semester_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'programsemester', ['program_semester_id'], ['id'])
    op.alter_column('courseschedule', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('courseschedule_program_semester_id_fkey', 'courseschedule', type_='foreignkey')
    op.create_foreign_key(None, 'courseschedule', 'programsemester', ['program_semester_id'], ['id'])
    op.alter_column('program', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('programsemester', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('programsemester', 'state',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('planned', 'current', 'finished', name='programsemesterstateenum'),
               nullable=False)
    op.alter_column('schedulesupportrequest', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schedulesupportrequest', 'handled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('studentprogramenrollment', 'enrolled_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studentprogramenrollment', 'status',
               existing_type=sa.VARCHAR(length=9),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'pedagogical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'theoretical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'practical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'laboratory_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'weekly_autonomous_work_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_subjectprerequisite_prerequisite_subject_id', table_name='subjectprerequisite')
    op.drop_index('ix_subjectprerequisite_subject_id', table_name='subjectprerequisite')
    op.drop_constraint(None, 'subjectprerequisite', type_='foreignkey')
    op.drop_constraint(None, 'subjectprerequisite', type_='foreignkey')
    op.create_foreign_key(None, 'subjectprerequisite', 'subject', ['prerequisite_subject_id'], ['id'])
    op.create_foreign_key(None, 'subjectprerequisite', 'subject', ['subject_id'], ['id'])
    op.alter_column('user', 'profile_image',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'subjectprerequisite', type_='foreignkey')
    op.drop_constraint(None, 'subjectprerequisite', type_='foreignkey')
    op.create_foreign_key(None, 'subjectprerequisite', 'subject', ['prerequisite_subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subjectprerequisite', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_subjectprerequisite_subject_id', 'subjectprerequisite', ['subject_id'], unique=False)
    op.create_index('ix_subjectprerequisite_prerequisite_subject_id', 'subjectprerequisite', ['prerequisite_subject_id'], unique=False)
    op.alter_column('subject', 'weekly_autonomous_work_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'laboratory_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'practical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'theoretical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'pedagogical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('studentprogramenrollment', 'status',
               existing_type=sa.VARCHAR(length=9),
               server_default=sa.text("'active'"),
               existing_nullable=False)
    op.alter_column('studentprogramenrollment', 'enrolled_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('student', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedulesupportrequest', 'handled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('schedulesupportrequest', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('programsemester', 'state',
               existing_type=sa.Enum('planned', 'current', 'finished', name='programsemesterstateenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('programsemester', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('program', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_constraint(None, 'courseschedule', type_='foreignkey')
    op.create_foreign_key('courseschedule_program_semester_id_fkey', 'courseschedule', 'programsemester', ['program_semester_id'], ['id'], ondelete='SET NULL')
    op.alter_column('courseschedule', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_program_semester_id_fkey', 'course', 'programsemester', ['program_semester_id'], ['id'], ondelete='SET NULL')
    op.alter_column('course', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appsetting', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
    op.alter_column('appsetting', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('appsetting', 'value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_assignmentsubmission_student_id'), table_name='assignmentsubmission')
    op.drop_index(op.f('ix_assignmentsubmission_assignment_id'), table_name='assignmentsubmission')
    op.drop_table('assignmentsubmission')
    op.drop_index(op.f('ix_coursematerial_course_id'), table_name='coursematerial')
    op.drop_table('coursematerial')
    op.drop_index(op.f('ix_courseassignment_course_id'), table_name='courseassignment')
    op.drop_table('courseassignment')
    # ### end Alembic commands ###
