"""
Revision ID: c8ceaaf089ed
Revises: d5e4c1a2ec7c
Create Date: 2025-12-25 23:27:21.399162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

program_semester_state_enum = sa.Enum(
    "planned",
    "current",
    "finished",
    name="programsemesterstateenum",
)

# revision identifiers, used by Alembic.
revision: str = 'c8ceaaf089ed'
down_revision: Union[str, None] = 'd5e4c1a2ec7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appsetting', 'value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('appsetting', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('appsetting', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('course', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('course_program_semester_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'programsemester', ['program_semester_id'], ['id'])
    op.alter_column('courseschedule', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('courseschedule_program_semester_id_fkey', 'courseschedule', type_='foreignkey')
    op.create_foreign_key(None, 'courseschedule', 'programsemester', ['program_semester_id'], ['id'])
    op.alter_column('program', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('programsemester', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    program_semester_state_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        'programsemester',
        'state',
        existing_type=sa.VARCHAR(length=20),
        type_=program_semester_state_enum,
        nullable=False,
        postgresql_using="state::programsemesterstateenum",
    )
    op.alter_column('schedulesupportrequest', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schedulesupportrequest', 'handled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('studentprogramenrollment', 'enrolled_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('studentprogramenrollment', 'status',
               existing_type=sa.VARCHAR(length=9),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'pedagogical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'theoretical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'practical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'laboratory_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subject', 'weekly_autonomous_work_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'profile_image',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subject', 'weekly_autonomous_work_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'laboratory_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'practical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'theoretical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('subject', 'pedagogical_hours_per_week',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('studentprogramenrollment', 'status',
               existing_type=sa.VARCHAR(length=9),
               server_default=sa.text("'active'"),
               existing_nullable=False)
    op.alter_column('studentprogramenrollment', 'enrolled_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('student', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedulesupportrequest', 'handled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('schedulesupportrequest', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('programsemester', 'state',
               existing_type=sa.Enum('planned', 'current', 'finished', name='programsemesterstateenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('programsemester', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('program', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_constraint(None, 'courseschedule', type_='foreignkey')
    op.create_foreign_key('courseschedule_program_semester_id_fkey', 'courseschedule', 'programsemester', ['program_semester_id'], ['id'], ondelete='SET NULL')
    op.alter_column('courseschedule', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_program_semester_id_fkey', 'course', 'programsemester', ['program_semester_id'], ['id'], ondelete='SET NULL')
    op.alter_column('course', 'program_semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appsetting', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
    op.alter_column('appsetting', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('appsetting', 'value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    program_semester_state_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
